language: go

env:
  global:
    - PKG_CONFIG_PATH=$HOME/gopath/src/github.com/Corundex/database_exporter/include

script:
  - export ARCH=$(uname -i)
  - sudo apt-get install libaio1
  - go get github.com/golang/glog
  - go get github.com/golang/protobuf/proto
  - go get github.com/prometheus/client_golang/prometheus
  - go get github.com/prometheus/client_model/go
  - go get github.com/prometheus/common/model
  - go get gopkg.in/yaml.v2
  - go get github.com/prometheus/client_golang/prometheus/promhttp
  - go get github.com/prometheus/common/expfmt
  - go get github.com/prometheus/common/version
  - go get github.com/denisenkom/go-mssqldb
  - go get github.com/go-sql-driver/mysql
  - go get github.com/kshvakov/clickhouse
  - go get github.com/lib/pq
  - go get github.com/go-goracle/goracle
  - go get github.com/mattn/go-sqlite3
  - go get github.com/couchbase/go_n1ql
  - make style
  - make vet
  - make test
  - make build
  - tar -czvf database_exporter.tar.gz database_exporter database_exporter.* ./config LICENSE VERSION

deploy:
  provider: releases
  api_key:
    secure: V557uoyEDg+dkidyJ96bZvwV6+raLFBnf81ZHKKHHVWNK87vQx2ZDkpQ5Uu5RLstmTi28HKk/rHLQxS0Rd1l2bgy6GIkS8S5oszgCVd82FnJG8bBTVextxP6vdVkzSHBSeH4/uIS9LVBWehK6DkkAcO9ntWR7mQwjyirtYaAKIsMeeUXvGpLezndiGXckBfezPs3h0rc4+X/ED+Qm73pNky1I+DPBxXR1f0whIuGFuH8gTMRsxJG6NlflKAEtpU9NDFdYVos8RKI6b3vNUc4AupYefP6Lhk+B0OiDu2qR25UpIk59G4YSwmyLyEnKAM0dOwxZGJenOAz/yUEQOHNpWkcR9E61LNiOFCmTJHGbHHpl6BhH2bn32CnV2l6pkQyqsVl3G6d+2ZMWHgqDf0eI+/DV+7CIzfSzlsrBwsNBBQYtnHRgODkv9QHNAhvmyYAbb0nkxsA129d2rF9Ig5KIwcvd1z6a9KYwVG6E7qgPfnqmKy9GW4BY5YTZRgXc/xYSc+ANjdQNSJpiri+kd/nBmwkFeykRU3a0pw+AtZUQk7noXPoSHHvVGT1pudvs9KhvwBEpzn1jbza07j9RYLGwavo6tO+gXR6f9f68jl18xb0915qk16Ftclppxz83nvG1Od7egIigncPc5yKpy53NYMgN3VPM6G0DnlBBhfh/aE=
  file: 
    - database_exporter.tar.gz
  skip_cleanup: true
  on:
    repo: Corundex/database_exporter
    branch: master
    tags: true
